### PR TITLE
Experimental matchers

### PR DESCRIPTION
**Pull request by MarekSuchanek**
Solves #7 and improves testing...

Will look at that with @hroncok before merge.

### CODE REVIEW

**Comment by hroncok** [comment]
(Rebased on top of master.)

**Comment by hroncok** [comment]
This passes (and fails where appropriate) for already submitted students. :tada:

**Comment by MarekSuchanek** [comment]
Great... I was convinced that betamax checks more on default. 

Do you please have some ideas about more/improvements? Or can I merge it now and also include it to `flask` tests?

**Comment by hroncok** [comment]
Let's wait for @kulikjak's ack.

**Pull request merged**
